# Релиз бинарников nekkus-hub в GitHub Releases.
# Триггер: git tag v* и push (например v0.1.0).
# В CI используется matrix: каждый раннер собирает только свою ОС (см. override-файлы).
# .goreleaser.yml

project_name: nekkus-hub

builds:
  - id: nekkus-hub
    main: ./cmd
    binary: nekkus-hub
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

release:
  github:
    owner: GalitskyKK
    name: nekkus-hub
  name_template: "v{{ .Version }}"
