# Ubuntu runner = amd64. Webview/systray — CGO, кросс-компиляция не поддерживается.
# .goreleaser.override.linux.yml
builds:
  - id: nekkus-hub
    main: ./cmd
    binary: nekkus-hub
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
