# macos-latest = Apple Silicon (arm64). CGO для webview/systray; darwin/amd64 не собираем.
# .goreleaser.override.darwin.yml
builds:
  - id: nekkus-hub
    main: ./cmd
    binary: nekkus-hub
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
