# Релиз бинарников nekkus-hub в GitHub Releases.
# Триггер: git tag v* и push (например v0.1.0).

project_name: nekkus-hub

before:
  hooks:
    - sh -c "cd frontend && npm install && npm run build"

builds:
  - id: nekkus-hub
    main: ./cmd
    binary: nekkus-hub
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

release:
  github:
    owner: GalitskyKK
    name: nekkus-hub
  name_template: "v{{ .Version }}"
